language: python
python:
     - "3.4"
     - "3.5"
install:
  - pip install -r src/python/national_voter_file/tests/requirements.txt
  - python setup.py install
script: nosetests src/python/national_voter_file/tests
